apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: lvdple9qd-python 
  janus-idp.io/tekton: lvdple9qd-python
  backstage.io/kubernetes-id: lvdple9qd-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lvdple9qd-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml