apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lvdple9qd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lvdple9qd-python 
  name: lvdple9qd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lvdple9qd-python 
